categorical_groups: {}
cell_type: LSTM
dropout: 0.1
embedding_labels: {}
embedding_paddings: []
embedding_sizes: {}
hidden_size: 30
learning_rate: 0.001
log_gradient_flow: false
log_interval: -1
log_val_interval: null
monotone_constaints: {}
n_plotting_samples: null
n_validation_samples: null
optimizer: ranger
optimizer_params: null
output_transformer: !!python/object:pytorch_forecasting.data.encoders.EncoderNormalizer
  center: true
  center_: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCgAAADE0Mjk4ODY4MDBxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAxNDI5ODg2
      ODAwcQFhLgEAAAAAAAAAXIw/QA==
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  max_length: null
  method: standard
  method_kwargs: {}
  scale_: !!python/object/apply:torch._utils._rebuild_tensor_v2
  - !!python/object/apply:torch.storage._load_from_bytes
    - !!binary |
      gAKKCmz8nEb5IGqoUBkugAJN6QMugAJ9cQAoWBAAAABwcm90b2NvbF92ZXJzaW9ucQFN6QNYDQAA
      AGxpdHRsZV9lbmRpYW5xAohYCgAAAHR5cGVfc2l6ZXNxA31xBChYBQAAAHNob3J0cQVLAlgDAAAA
      aW50cQZLBFgEAAAAbG9uZ3EHSwR1dS6AAihYBwAAAHN0b3JhZ2VxAGN0b3JjaApGbG9hdFN0b3Jh
      Z2UKcQFYCgAAADE0MzMyNzc4MjRxAlgDAAAAY3B1cQNLAU50cQRRLoACXXEAWAoAAAAxNDMzMjc3
      ODI0cQFhLgEAAAAAAAAAXa70PQ==
  - 0
  - !!python/tuple []
  - !!python/tuple []
  - false
  - !!python/object/apply:collections.OrderedDict
    - []
  transformation: log
reduce_on_plateau_min_lr: 1.0e-05
reduce_on_plateau_patience: 1000
reduce_on_plateau_reduction: 2.0
rnn_layers: 4
static_categoricals: []
static_reals: []
target: price
target_lags: {}
time_varying_categoricals_decoder: []
time_varying_categoricals_encoder: []
time_varying_reals_decoder: []
time_varying_reals_encoder:
- price
weight_decay: 0.0
x_categoricals: []
x_reals:
- price
